version: '3'
services:
  backend:
    build: backend/
    restart: on-failure
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app/src
  frontend:
    build: frontend/
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend